version: "3"

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:6.0.0-php8.0-apache
     ports:
       - "8008:80"
     networks:
       - wgnet
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: Nettantra@db

   db:
     image: mysql
     restart: always
     networks:
       - wgnet
     environment:
       MYSQL_ROOT_PASSWORD: Nettantra@1234
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: Nettantra@db
   app:
      image: badalsahu/gatsby
      restart: always
      networks:
        - wgnet
      ports: 
        - "8000:80"

networks:
    wgnet:
       external: true
